import type { Scene, VocabularyItem } from './types';
import { polygon as p, region as r } from './hotspots';

const source = (slug: string) => `https://dictionary.cambridge.org/pronunciation/english/${slug}`;

function word(
  id: string,
  text: string,
  ipa: string,
  meaning: string,
  example: string,
  aliases: string[] = [],
  sources: string[] = [text.replaceAll(' ', '-')],
): VocabularyItem {
  return {
    id,
    word: text,
    partOfSpeech: 'noun',
    britishIPA: ipa,
    chineseMeaning: meaning,
    exampleSentence: example,
    acceptedAnswers: aliases,
    audioText: text,
    ipaSource: source(sources[0]),
    ipaSources: sources.map(source),
  };
}

export const expandedVocabulary: VocabularyItem[] = [
  word('living-room-sofa', 'sofa', '/ˈsəʊ.fə/', '沙发', 'The sofa is in the centre of the living room.', ['sofas', 'settee', 'settees']),
  word('living-room-armchair', 'armchair', '/ˈɑːm.tʃeə/', '扶手椅', 'The armchair is beside the sofa.', ['armchairs']),
  word('living-room-coffee-table', 'coffee table', '/ˈkɒf.i ˌteɪ.bəl/', '茶几', 'Put the remote on the coffee table.', ['coffee tables'], ['coffee', 'table']),
  word('living-room-television', 'television', '/ˈtel.ɪ.vɪʒ.ən/', '电视', 'The television is opposite the sofa.', ['televisions', 'TV', 'TV set']),
  word('living-room-floor-lamp', 'floor lamp', '/ˈflɔː ˌlæmp/', '落地灯', 'The floor lamp gives a soft light.', ['floor lamps', 'standing lamp'], ['floor', 'lamp']),
  word('living-room-rug', 'rug', '/rʌɡ/', '地毯', 'A large rug covers the wooden floor.', ['rugs']),
  word('living-room-bookshelf', 'bookshelf', '/ˈbʊk.ʃelf/', '书架', 'The bookshelf holds books and ornaments.', ['bookshelves', 'bookcase', 'bookcases']),
  word('living-room-cushion', 'cushion', '/ˈkʊʃ.ən/', '靠垫', 'There is a green cushion on the sofa.', ['cushions', 'throw pillow']),
  word('living-room-curtain', 'curtain', '/ˈkɜː.tən/', '窗帘', 'The curtain hangs beside the window.', ['curtains']),
  word('living-room-wall-clock', 'wall clock', '/ˈwɔːl ˌklɒk/', '挂钟', 'The wall clock shows the time clearly.', ['wall clocks', 'clock', 'clocks'], ['wall', 'clock']),

  word('bathroom-bathtub', 'bathtub', '/ˈbɑːθ.tʌb/', '浴缸', 'Fill the bathtub with warm water.', ['bathtubs', 'bath', 'baths']),
  word('bathroom-shower', 'shower', '/ˈʃaʊ.ər/', '淋浴间', 'The shower has a clear glass door.', ['showers', 'shower cubicle']),
  word('bathroom-toilet', 'toilet', '/ˈtɔɪ.lət/', '马桶', 'The toilet is beside the laundry basket.', ['toilets', 'loo']),
  word('bathroom-sink', 'sink', '/sɪŋk/', '洗手池', 'Wash your hands in the sink.', ['sinks', 'basin', 'washbasin']),
  word('bathroom-mirror', 'mirror', '/ˈmɪr.ər/', '镜子', 'The mirror hangs above the sink.', ['mirrors']),
  word('bathroom-tap', 'tap', '/tæp/', '水龙头', 'Turn off the tap after washing.', ['taps', 'faucet', 'faucets']),
  word('bathroom-towel', 'towel', '/taʊəl/', '毛巾', 'The clean towel is on the rail.', ['towels', 'bath towel']),
  word('bathroom-bath-mat', 'bath mat', '/ˈbɑːθ ˌmæt/', '浴室防滑垫', 'Step onto the bath mat carefully.', ['bath mats', 'bathroom mat'], ['bath', 'mat']),
  word('bathroom-laundry-basket', 'laundry basket', '/ˈlɔːn.dri ˌbɑː.skɪt/', '洗衣篮', 'Put the used towel in the laundry basket.', ['laundry baskets', 'washing basket'], ['laundry', 'basket']),
  word('bathroom-cabinet', 'bathroom cabinet', '/ˈbɑːθ.ruːm ˌkæb.ɪ.nət/', '浴室柜', 'Cleaning products are kept in the bathroom cabinet.', ['bathroom cabinets', 'cabinet', 'vanity unit'], ['bathroom', 'cabinet']),

  word('laundry-washing-machine', 'washing machine', '/ˈwɒʃ.ɪŋ məˌʃiːn/', '洗衣机', 'Put the clothes in the washing machine.', ['washing machines', 'washer'], ['washing-machine']),
  word('laundry-tumble-dryer', 'tumble dryer', '/ˈtʌm.bəl ˌdraɪ.ər/', '滚筒式烘干机', 'The towels are drying in the tumble dryer.', ['tumble dryers', 'dryer', 'clothes dryer'], ['tumble-dryer']),
  word('laundry-basket', 'laundry basket', '/ˈlɔːn.dri ˌbɑː.skɪt/', '洗衣篮', 'The laundry basket is full of clean clothes.', ['laundry baskets', 'washing basket'], ['laundry', 'basket']),
  word('laundry-ironing-board', 'ironing board', '/ˈaɪə.nɪŋ ˌbɔːd/', '熨衣板', 'Open the ironing board before you start.', ['ironing boards'], ['ironing-board']),
  word('laundry-iron', 'iron', '/ˈaɪən/', '熨斗', 'The iron is resting on the board.', ['irons', 'steam iron']),
  word('laundry-clothes-airer', 'clothes airer', '/ˈkləʊðz ˌeə.rər/', '晾衣架', 'Hang the shirt on the clothes airer.', ['clothes airers', 'drying rack', 'clothes rack'], ['clothes', 'airer']),
  word('laundry-detergent', 'detergent', '/dɪˈtɜː.dʒənt/', '洗衣液', 'Add detergent before starting the wash.', ['detergents', 'laundry detergent']),
  word('laundry-fabric-softener', 'fabric softener', '/ˈfæb.rɪk ˌsɒf.ən.ər/', '衣物柔顺剂', 'The fabric softener makes the towels feel softer.', ['fabric softeners', 'softener'], ['fabric', 'softener']),
  word('laundry-sink', 'sink', '/sɪŋk/', '水槽', 'Rinse the cloth in the sink.', ['sinks', 'utility sink']),
  word('laundry-storage-cupboard', 'storage cupboard', '/ˈstɔː.rɪdʒ ˌkʌb.əd/', '储物柜', 'The storage cupboard keeps the room tidy.', ['storage cupboards', 'cupboard', 'cabinet'], ['storage', 'cupboard']),

  word('supermarket-shopping-trolley', 'shopping trolley', '/ˈʃɒp.ɪŋ ˌtrɒl.i/', '购物车', 'Push the shopping trolley down the aisle.', ['shopping trolleys', 'trolley', 'cart'], ['shopping', 'trolley']),
  word('supermarket-shopping-basket', 'shopping basket', '/ˈʃɒp.ɪŋ ˌbɑː.skɪt/', '购物篮', 'Use a shopping basket for a few items.', ['shopping baskets', 'basket', 'hand basket'], ['shopping', 'basket']),
  word('supermarket-2-apple', 'apple', '/ˈæp.əl/', '苹果', 'Choose a fresh apple from the display.', ['apples']),
  word('supermarket-banana', 'banana', '/bəˈnɑː.nə/', '香蕉', 'The bananas are beside the apples.', ['bananas']),
  word('supermarket-bread', 'bread', '/bred/', '面包', 'This loaf of bread looks fresh.', ['loaf', 'bread loaf', 'loaf of bread']),
  word('supermarket-milk', 'milk', '/mɪlk/', '牛奶', 'Pick up a bottle of milk.', ['milk bottle', 'bottle of milk']),
  word('supermarket-eggs', 'eggs', '/eɡz/', '鸡蛋', 'Check that the eggs are not cracked.', ['egg', 'egg carton', 'carton of eggs']),
  word('supermarket-cheese', 'cheese', '/tʃiːz/', '奶酪', 'The cheese is next to the eggs.', ['block of cheese']),
  word('supermarket-cereal', 'cereal', '/ˈsɪə.ri.əl/', '早餐麦片', 'Choose a box of cereal for breakfast.', ['cereals', 'cereal box', 'box of cereal']),
  word('supermarket-tin', 'tin', '/tɪn/', '罐头', 'Put the tin in the trolley.', ['tins', 'can', 'cans', 'tin can']),

  word('cafe-coffee-cup', 'coffee cup', '/ˈkɒf.i ˌkʌp/', '咖啡杯', 'The coffee cup is warm in my hands.', ['coffee cups', 'cup'], ['coffee', 'cup']),
  word('cafe-saucer', 'saucer', '/ˈsɔː.sər/', '茶碟', 'The cup sits on a white saucer.', ['saucers']),
  word('cafe-teaspoon', 'teaspoon', '/ˈtiː.spuːn/', '茶匙', 'Stir the coffee with a teaspoon.', ['teaspoons', 'spoon']),
  word('cafe-teapot', 'teapot', '/ˈtiː.pɒt/', '茶壶', 'The teapot holds enough tea for two.', ['teapots']),
  word('cafe-croissant', 'croissant', '/ˈkwæs.ɒ̃/', '羊角面包', 'The croissant is crisp and buttery.', ['croissants']),
  word('cafe-cake', 'cake', '/keɪk/', '蛋糕', 'I ordered a slice of chocolate cake.', ['cakes', 'cake slice', 'slice of cake']),
  word('cafe-espresso-machine', 'espresso machine', '/eˈspres.əʊ məˌʃiːn/', '意式咖啡机', 'The barista uses the espresso machine.', ['espresso machines', 'coffee machine'], ['espresso', 'machine']),
  word('cafe-coffee-grinder', 'coffee grinder', '/ˈkɒf.i ˌɡraɪn.dər/', '咖啡研磨机', 'The coffee grinder is beside the machine.', ['coffee grinders', 'grinder'], ['coffee', 'grinder']),
  word('cafe-milk-jug', 'milk jug', '/ˈmɪlk ˌdʒʌɡ/', '奶壶', 'Pour a little milk from the jug.', ['milk jugs', 'jug', 'milk pitcher'], ['milk', 'jug']),
  word('cafe-bar-stool', 'bar stool', '/ˈbɑː ˌstuːl/', '吧台凳', 'Take a seat on the bar stool.', ['bar stools', 'stool'], ['bar', 'stool']),

  word('pool-swimming-pool', 'swimming pool', '/ˈswɪm.ɪŋ ˌpuːl/', '游泳池', 'The swimming pool has several lanes.', ['swimming pools', 'pool'], ['swimming', 'pool']),
  word('pool-diving-board', 'diving board', '/ˈdaɪ.vɪŋ ˌbɔːd/', '跳水板', 'Walk carefully along the diving board.', ['diving boards'], ['diving-board']),
  word('pool-lane-rope', 'lane rope', '/ˈleɪn ˌrəʊp/', '泳道线', 'The lane rope separates the swimmers.', ['lane ropes', 'lane line'], ['lane', 'rope']),
  word('pool-starting-block', 'starting block', '/ˈstɑː.tɪŋ ˌblɒk/', '出发台', 'The swimmer waits on the starting block.', ['starting blocks'], ['starting-block']),
  word('pool-ladder', 'ladder', '/ˈlæd.ər/', '扶梯', 'Use the ladder to climb out of the pool.', ['ladders', 'pool ladder']),
  word('pool-lifebuoy', 'lifebuoy', '/ˈlaɪf.bɔɪ/', '救生圈', 'The lifebuoy hangs on the wall.', ['lifebuoys', 'life buoy', 'life ring']),
  word('pool-kickboard', 'kickboard', '/ˈkɪk.bɔːd/', '浮板', 'Hold the kickboard while practising your kick.', ['kickboards', 'swimming board']),
  word('pool-goggles', 'swimming goggles', '/ˈswɪm.ɪŋ ˌɡɒɡ.əlz/', '泳镜', 'Wear swimming goggles to protect your eyes.', ['goggles', 'swim goggles'], ['swimming', 'goggles']),
  word('pool-cap', 'swimming cap', '/ˈswɪm.ɪŋ ˌkæp/', '泳帽', 'Put on your swimming cap before entering the pool.', ['swimming caps', 'swim cap', 'cap'], ['swimming', 'cap']),
  word('pool-towel', 'towel', '/taʊəl/', '毛巾', 'Dry yourself with the folded towel.', ['towels', 'swimming towel']),

  word('skincare-cleanser', 'cleanser', '/ˈklen.zər/', '洁面产品', 'Wash your face with a gentle cleanser.', ['cleansers', 'face cleanser']),
  word('skincare-toner', 'toner', '/ˈtəʊ.nər/', '爽肤水', 'Apply the toner after cleansing.', ['toners', 'face toner']),
  word('skincare-serum', 'face serum', '/ˈfeɪs ˌsɪə.rəm/', '面部精华', 'Use a few drops of face serum.', ['serum', 'facial serum'], ['face', 'serum']),
  word('skincare-moisturiser', 'moisturiser', '/ˈmɔɪs.tʃər.aɪ.zər/', '保湿霜', 'Finish your routine with moisturiser.', ['moisturisers', 'moisturizer', 'face cream']),
  word('skincare-eye-cream', 'eye cream', '/ˈaɪ ˌkriːm/', '眼霜', 'Dab a small amount of eye cream under each eye.', ['eye creams'], ['eye', 'cream']),
  word('skincare-sunscreen', 'sunscreen', '/ˈsʌn.skriːn/', '防晒霜', 'Apply sunscreen before going outside.', ['sunscreens', 'sun cream', 'sunblock']),
  word('skincare-cotton-pads', 'cotton pads', '/ˈkɒt.ən ˌpædz/', '化妆棉', 'Use cotton pads to apply the toner.', ['cotton pad', 'pads'], ['cotton', 'pad']),
  word('skincare-facial-roller', 'facial roller', '/ˈfeɪ.ʃəl ˌrəʊ.lər/', '面部滚轮', 'Move the facial roller gently across your skin.', ['facial rollers', 'face roller'], ['facial', 'roller']),
  word('skincare-headband', 'headband', '/ˈhed.bænd/', '发带', 'The headband keeps hair away from your face.', ['headbands', 'hair band']),
  word('skincare-mirror', 'mirror', '/ˈmɪr.ər/', '镜子', 'Check your skin in the mirror.', ['mirrors', 'vanity mirror']),

  word('hotel-bed', 'bed', '/bed/', '床', 'The bed is ready for the guest.', ['beds', 'hotel bed']),
  word('hotel-pillow', 'pillow', '/ˈpɪl.əʊ/', '枕头', 'The pillow is soft and clean.', ['pillows']),
  word('hotel-bedside-table', 'bedside table', '/ˈbed.saɪd ˌteɪ.bəl/', '床头柜', 'The lamp is on the bedside table.', ['bedside tables', 'nightstand'], ['bedside', 'table']),
  word('hotel-bedside-lamp', 'bedside lamp', '/ˈbed.saɪd ˌlæmp/', '床头灯', 'Switch off the bedside lamp before sleeping.', ['bedside lamps', 'lamp'], ['bedside', 'lamp']),
  word('hotel-wardrobe', 'wardrobe', '/ˈwɔː.drəʊb/', '衣柜', 'Hang your coat in the wardrobe.', ['wardrobes', 'closet']),
  word('hotel-suitcase', 'suitcase', '/ˈsuːt.keɪs/', '行李箱', 'Open the suitcase on the luggage rack.', ['suitcases', 'case', 'luggage']),
  word('hotel-luggage-rack', 'luggage rack', '/ˈlʌɡ.ɪdʒ ˌræk/', '行李架', 'Place your suitcase on the luggage rack.', ['luggage racks', 'suitcase stand'], ['luggage', 'rack']),
  word('hotel-desk', 'desk', '/desk/', '书桌', 'The key card is on the desk.', ['desks', 'writing desk']),
  word('hotel-chair', 'chair', '/tʃeər/', '椅子', 'Pull the chair up to the desk.', ['chairs', 'desk chair']),
  word('hotel-kettle', 'kettle', '/ˈket.əl/', '烧水壶', 'Use the kettle to make a cup of tea.', ['kettles', 'electric kettle']),

  word('underwater-sea-turtle', 'sea turtle', '/ˈsiː ˌtɜː.təl/', '海龟', 'The sea turtle glides above the reef.', ['sea turtles', 'turtle'], ['sea', 'turtle']),
  word('underwater-stingray', 'stingray', '/ˈstɪŋ.reɪ/', '黄貂鱼', 'A stingray swims through the clear water.', ['stingrays', 'ray']),
  word('underwater-octopus', 'octopus', '/ˈɒk.tə.pəs/', '章鱼', 'The octopus rests beside the rocks.', ['octopuses', 'octopi']),
  word('underwater-seahorse', 'seahorse', '/ˈsiː.hɔːs/', '海马', 'The seahorse holds onto the seaweed.', ['seahorses', 'sea horse']),
  word('underwater-clownfish', 'clownfish', '/ˈklaʊn.fɪʃ/', '小丑鱼', 'The clownfish hide among the coral.', ['clown fish', 'clownfishes']),
  word('underwater-pufferfish', 'pufferfish', '/ˈpʌf.ə.fɪʃ/', '河豚', 'The pufferfish has a round body.', ['puffer fish', 'pufferfishes']),
  word('underwater-jellyfish', 'jellyfish', '/ˈdʒel.i.fɪʃ/', '水母', 'The jellyfish floats in the open water.', ['jellyfishes']),
  word('underwater-starfish', 'starfish', '/ˈstɑː.fɪʃ/', '海星', 'A starfish lies on the sandy seabed.', ['starfishes', 'sea star']),
  word('underwater-crab', 'crab', '/kræb/', '螃蟹', 'The crab walks across the sand.', ['crabs']),
  word('underwater-coral', 'coral', '/ˈkɒr.əl/', '珊瑚', 'Colourful coral grows on the reef.', ['corals', 'coral reef']),
];

export const expandedScenes: Scene[] = [
  {
    id: 'living-room-1', topicId: 'living-room', title: 'Living Room', image: 'scenes/home-living/living-room-1.webp',
    thumbnail: 'scenes/thumbnails/living-room-1-thumb.webp', imageWidth: 1536, imageHeight: 1024, published: true, assetStatus: 'final', nextSceneId: null,
    vocabularyIds: ['living-room-sofa', 'living-room-armchair', 'living-room-coffee-table', 'living-room-television', 'living-room-floor-lamp', 'living-room-rug', 'living-room-bookshelf', 'living-room-cushion', 'living-room-curtain', 'living-room-wall-clock'],
    hotspots: [r('living-room-sofa', 350, 326, 419, 281), r('living-room-armchair', 0, 417, 294, 437), r('living-room-coffee-table', 503, 532, 240, 299, 'ellipse'), r('living-room-television', 897, 241, 103, 390), r('living-room-floor-lamp', 281, 187, 98, 376), r('living-room-rug', 5, 826, 980, 141), r('living-room-bookshelf', 27, 24, 143, 504), r('living-room-cushion', 382, 349, 75, 132), r('living-room-curtain', 837, 0, 105, 545), r('living-room-wall-clock', 515, 48, 118, 149, 'ellipse')],
  },
  {
    id: 'bathroom-1', topicId: 'bathroom', title: 'Bathroom', image: 'scenes/home-living/bathroom-1.webp',
    thumbnail: 'scenes/thumbnails/bathroom-1-thumb.webp', imageWidth: 1536, imageHeight: 1024, published: true, assetStatus: 'final', nextSceneId: null,
    vocabularyIds: ['bathroom-bathtub', 'bathroom-shower', 'bathroom-toilet', 'bathroom-sink', 'bathroom-mirror', 'bathroom-tap', 'bathroom-towel', 'bathroom-bath-mat', 'bathroom-laundry-basket', 'bathroom-cabinet'],
    hotspots: [r('bathroom-bathtub', 0, 476, 273, 314), r('bathroom-shower', 107, 0, 282, 704), r('bathroom-toilet', 433, 421, 112, 326), r('bathroom-sink', 744, 558, 256, 74), r('bathroom-mirror', 858, 0, 142, 416), r('bathroom-tap', 865, 429, 72, 137), r('bathroom-towel', 584, 343, 116, 237), r('bathroom-bath-mat', 184, 786, 246, 178), r('bathroom-laundry-basket', 552, 523, 99, 222, 'ellipse'), r('bathroom-cabinet', 742, 568, 258, 335)],
  },
  {
    id: 'laundry-room-1', topicId: 'laundry-room', title: 'Laundry Room', image: 'scenes/home-living/laundry-room-1.webp',
    thumbnail: 'scenes/thumbnails/laundry-room-1-thumb.webp', imageWidth: 1536, imageHeight: 1024, published: true, assetStatus: 'final', nextSceneId: null,
    vocabularyIds: ['laundry-washing-machine', 'laundry-tumble-dryer', 'laundry-basket', 'laundry-ironing-board', 'laundry-iron', 'laundry-clothes-airer', 'laundry-detergent', 'laundry-fabric-softener', 'laundry-sink', 'laundry-storage-cupboard'],
    hotspots: [r('laundry-washing-machine', 12, 408, 260, 378), r('laundry-tumble-dryer', 276, 411, 255, 372), r('laundry-basket', 410, 620, 204, 304, 'ellipse'), p('laundry-ironing-board', [[580,493],[748,482],[748,633],[620,650]]), r('laundry-iron', 771, 333, 73, 253), r('laundry-clothes-airer', 819, 269, 181, 448), r('laundry-detergent', 98, 189, 56, 163), r('laundry-fabric-softener', 155, 208, 54, 144), r('laundry-sink', 365, 292, 190, 113), r('laundry-storage-cupboard', 568, 28, 211, 531)],
  },
  {
    id: 'supermarket-2', topicId: 'supermarket', title: 'Supermarket', image: 'scenes/food-dining/supermarket-1.webp',
    thumbnail: 'scenes/thumbnails/supermarket-1-thumb.webp', imageWidth: 1536, imageHeight: 1024, published: true, assetStatus: 'final', nextSceneId: null,
    vocabularyIds: ['supermarket-shopping-trolley', 'supermarket-shopping-basket', 'supermarket-2-apple', 'supermarket-banana', 'supermarket-bread', 'supermarket-milk', 'supermarket-eggs', 'supermarket-cheese', 'supermarket-cereal', 'supermarket-tin'],
    hotspots: [p('supermarket-shopping-trolley', [[0,397],[308,390],[353,820],[299,952],[37,948],[0,877]]), r('supermarket-shopping-basket', 250, 733, 225, 239), r('supermarket-2-apple', 0, 308, 128, 139), r('supermarket-banana', 89, 311, 142, 145), r('supermarket-bread', 387, 530, 166, 173), r('supermarket-milk', 551, 440, 78, 262), r('supermarket-eggs', 628, 575, 128, 143), r('supermarket-cheese', 748, 620, 106, 112), r('supermarket-cereal', 649, 414, 101, 195), r('supermarket-tin', 834, 518, 62, 153)],
  },
  {
    id: 'cafe-1', topicId: 'cafe', title: 'Café', image: 'scenes/food-dining/cafe-1.webp',
    thumbnail: 'scenes/thumbnails/cafe-1-thumb.webp', imageWidth: 1536, imageHeight: 1024, published: true, assetStatus: 'final', nextSceneId: null,
    vocabularyIds: ['cafe-coffee-cup', 'cafe-saucer', 'cafe-teaspoon', 'cafe-teapot', 'cafe-croissant', 'cafe-cake', 'cafe-espresso-machine', 'cafe-coffee-grinder', 'cafe-milk-jug', 'cafe-bar-stool'],
    hotspots: [r('cafe-coffee-cup', 288, 648, 188, 235, 'ellipse'), r('cafe-saucer', 272, 806, 226, 105, 'ellipse'), p('cafe-teaspoon', [[492,824],[570,789],[604,807],[529,901],[495,911]]), r('cafe-teapot', 325, 520, 198, 211), r('cafe-croissant', 44, 642, 218, 151), r('cafe-cake', 591, 570, 169, 199), r('cafe-espresso-machine', 332, 38, 294, 315), r('cafe-coffee-grinder', 672, 32, 79, 325), r('cafe-milk-jug', 744, 228, 64, 134), r('cafe-bar-stool', 828, 424, 172, 576)],
  },
  {
    id: 'swimming-pool-1', topicId: 'swimming-pool', title: 'Swimming Pool', image: 'scenes/sports-fitness/swimming-pool-1.webp',
    thumbnail: 'scenes/thumbnails/swimming-pool-1-thumb.webp', imageWidth: 1536, imageHeight: 1024, published: true, assetStatus: 'final', nextSceneId: null,
    vocabularyIds: ['pool-swimming-pool', 'pool-diving-board', 'pool-lane-rope', 'pool-starting-block', 'pool-ladder', 'pool-lifebuoy', 'pool-kickboard', 'pool-goggles', 'pool-cap', 'pool-towel'],
    hotspots: [r('pool-swimming-pool', 24, 636, 622, 158), p('pool-diving-board', [[53,83],[264,64],[310,112],[299,158],[112,205],[54,178]]), r('pool-lane-rope', 0, 451, 714, 165), r('pool-starting-block', 195, 251, 154, 151), r('pool-ladder', 731, 314, 104, 233), r('pool-lifebuoy', 657, 119, 83, 190, 'ellipse'), r('pool-kickboard', 844, 145, 69, 168), r('pool-goggles', 345, 780, 142, 111, 'ellipse'), r('pool-cap', 523, 753, 149, 136, 'ellipse'), r('pool-towel', 673, 712, 204, 174)],
  },
  {
    id: 'skin-care-1', topicId: 'skin-care', title: 'Skincare', image: 'scenes/beauty-personal-care/skincare-1.webp',
    thumbnail: 'scenes/thumbnails/skincare-1-thumb.webp', imageWidth: 1536, imageHeight: 1024, published: true, assetStatus: 'final', nextSceneId: null,
    vocabularyIds: ['skincare-cleanser', 'skincare-toner', 'skincare-serum', 'skincare-moisturiser', 'skincare-eye-cream', 'skincare-sunscreen', 'skincare-cotton-pads', 'skincare-facial-roller', 'skincare-headband', 'skincare-mirror'],
    hotspots: [r('skincare-cleanser', 151, 282, 99, 387), r('skincare-toner', 260, 267, 99, 407), r('skincare-serum', 361, 373, 80, 332), r('skincare-moisturiser', 496, 524, 96, 208), r('skincare-eye-cream', 646, 460, 64, 273), r('skincare-sunscreen', 731, 387, 75, 343), r('skincare-cotton-pads', 5, 337, 92, 315), p('skincare-facial-roller', [[350,768],[387,724],[548,835],[510,903]]), r('skincare-headband', 596, 746, 241, 175, 'ellipse'), r('skincare-mirror', 535, 0, 251, 565, 'ellipse')],
  },
  {
    id: 'hotel-room-1', topicId: 'hotel', title: 'Hotel Room', image: 'scenes/travel-transport/hotel-room-1.webp',
    thumbnail: 'scenes/thumbnails/hotel-room-1-thumb.webp', imageWidth: 1536, imageHeight: 1024, published: true, assetStatus: 'final', nextSceneId: null,
    vocabularyIds: ['hotel-bed', 'hotel-pillow', 'hotel-bedside-table', 'hotel-bedside-lamp', 'hotel-wardrobe', 'hotel-suitcase', 'hotel-luggage-rack', 'hotel-desk', 'hotel-chair', 'hotel-kettle'],
    hotspots: [r('hotel-bed', 311, 326, 389, 405), r('hotel-pillow', 366, 335, 183, 156), r('hotel-bedside-table', 701, 472, 76, 167), r('hotel-bedside-lamp', 702, 321, 67, 164), r('hotel-wardrobe', 49, 29, 233, 514), r('hotel-suitcase', 61, 449, 177, 280), r('hotel-luggage-rack', 63, 742, 191, 202), r('hotel-desk', 835, 474, 165, 526), p('hotel-chair', [[776,572],[847,539],[898,595],[897,1000],[787,1000]]), r('hotel-kettle', 915, 459, 70, 143)],
  },
  {
    id: 'underwater-1', topicId: 'underwater', title: 'Underwater World', image: 'scenes/animals/underwater-world-1.webp',
    thumbnail: 'scenes/thumbnails/underwater-world-1-thumb.webp', imageWidth: 1536, imageHeight: 1024, published: true, assetStatus: 'final', nextSceneId: null,
    vocabularyIds: ['underwater-sea-turtle', 'underwater-stingray', 'underwater-octopus', 'underwater-seahorse', 'underwater-clownfish', 'underwater-pufferfish', 'underwater-jellyfish', 'underwater-starfish', 'underwater-crab', 'underwater-coral'],
    hotspots: [p('underwater-sea-turtle', [[12,35],[159,25],[283,75],[326,165],[266,269],[141,243],[77,169]]), p('underwater-stingray', [[600,100],[714,40],[876,57],[1000,121],[1000,226],[842,270],[715,231]]), r('underwater-octopus', 0, 543, 307, 404), r('underwater-seahorse', 139, 310, 86, 224), r('underwater-clownfish', 761, 444, 205, 203), r('underwater-pufferfish', 421, 368, 128, 207, 'ellipse'), r('underwater-jellyfish', 394, 70, 116, 270), r('underwater-starfish', 373, 817, 132, 183), r('underwater-crab', 538, 813, 158, 187), p('underwater-coral', [[628,484],[687,423],[749,449],[748,715],[681,750],[631,682]])],
  },
];
